### ISSUE TITLE
Closing navigation view with close button is not working(Android)

### ISSUE THREAD

**Issue by gadishimwe** [eopeter/flutter_mapbox_navigation#69]
Hi @eopeter. The closing button on the navigation view is not working. I had to use the back button in order to close it.

V0.0.12

**Comment by eopeter** [comment]
this is resolved

**Comment by usamaKabir07** [comment]
hi @eopeter I'm still having the same issue, can you help, i have a latest version of plugin installed
